return {
--     "folke/noice.nvim",
--     event = "VeryLazy",
--     opts = {
--         lsp = {
--             -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
--             override = {
--             ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--             ["vim.lsp.util.stylize_markdown"] = true,
--             ["cmp.entry.get_documentation"] = true,
--             },
--         },
--         -- Show @recording messages as a notify message (https://github.com/folke/noice.nvim/wiki/Configuration-Recipes)
--         routes = {
--             {
--                 view = "notify",
--                 filter = { event = "msg_showmode" },
--             },
--         },
--         -- cmdline = {
--         --     view = "cmdline",
--         -- },
--         -- you can enable a preset for easier configuration
--         presets = {
--             bottom_search = true, -- use a classic bottom cmdline for search
--             command_palette = true, -- position the cmdline and popupmenu together
--             long_message_to_split = true, -- long messages will be sent to a split
--             inc_rename = false, -- enables an input dialog for inc-rename.nvim
--             lsp_doc_border = true, -- add a border to hover docs and signature help
--         },
--         -- messages = {
--         --     backend = "mini"
--         -- }
--     },
--     dependencies = {
--         -- https://github.com/smjonas/inc-rename.nvim
--         -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
--         "MunifTanjim/nui.nvim",
--         -- OPTIONAL:
--         --   `nvim-notify` is only needed, if you want to use the notification view.
--         --   If not available, we use `mini` as the fallback
--         {
--             "rcarriga/nvim-notify",
--             keys = {
--                 {"<leader>d", ":lua require('notify').dismiss()<CR>", desc = "Dismiss notification"},
--             },
--             opts = {
--                 render = "compact", -- default, compact, minimal, simple
--                 stages = "fade", -- fade, fade_in_slide_out, slide, static
--                 background_colour = "#000000",
--                 timeout = 2500,
--                 top_down = true,
--             },
--         },
--     }
}
